# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: roqmarcelo
description: "Consultor Independente e Freelancer focado em projetos utilizando Java EE e ASP.NET"
keywords: "JavaEE, ASP.NET MVC, Engenheiro de Software, Programador, Freelancer, Consultor"
url: http://roqmarcelo.github.io
baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/roqmarcelo/roqmarcelo.github.io
disqus_shortname: "roqmarcelo"
disqus_site_shortname: "roqmarcelo"

# Author settings
author:
  name      : Roque Marcelo Santana dos Santos
  job       : Desenvolvedor de Software
  bio       : "Desenvolvedor de Software com mais de 6 anos de experiência nas plataformas Java e .NET."
  thumb     : /images/author.jpg
  email     : roque.santoro@gmail.com
  url       : http://roqmarcelo.github.io
  github    : http://github.com/roqmarcelo
  twitter   : http://twitter.com/roqmarcelo
  linkedin  : http://linkedin.com/in/roqmarcelo

# navbar pages
navbar:
  - slug: sobre
    title: Sobre
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
